cmake_minimum_required(VERSION 3.18 FATAL_ERROR)

set(HYPERGRAPH_VERSION "1.0")
set(HYPERGRAPH_LANGUAGES )
set(HYPERGRAPH_CODESIGNING )
set(SW_VERS "")
set(UNAME_M "")

if (APPLE)
    list(APPEND HYPERGRAPH_LANGUAGES "C")
    list(APPEND HYPERGRAPH_LANGUAGES "CXX")
    list(APPEND HYPERGRAPH_LANGUAGES "OBJC")
    list(APPEND HYPERGRAPH_LANGUAGES "OBJCXX")
    execute_process(COMMAND sw_vers -productVersion OUTPUT_VARIABLE SW_VERS ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    if ("${CMAKE_GENERATOR}" MATCHES "Xcode")
        execute_process(COMMAND uname -m OUTPUT_VARIABLE UNAME_M ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        if (NOT "$ENV{SYSROOT}" STREQUAL "")
            set(SYSROOT "$ENV{SYSROOT}")
        else()
            execute_process(COMMAND xcodebuild -version -sdk macosx Path OUTPUT_VARIABLE SYSROOT ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif()
        if (NOT EXISTS "${SYSROOT}")
            message(FATAL_ERROR "SYSROOT does not exist!")
        endif()
        set(CMAKE_OSX_SYSROOT "${SYSROOT}" CACHE STRING "CMAKE_OSX_SYSROOT" FORCE)
        if ("${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
            if ("${UNAME_M}" MATCHES "arm")
                set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            else()
                set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD)" CACHE STRING "CMAKE_OSX_ARCHITECTURES" FORCE)
            endif()
        endif()
    endif()
    execute_process(COMMAND security find-identity -v -p codesigning OUTPUT_VARIABLE SECURITY_FOUND_IDENTITY ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(PATTERN " ")
    foreach (IDX RANGE 1 40 1)
        string(APPEND PATTERN "[a-fA-F0-9]")
    endforeach()
    string(APPEND PATTERN " ")
    string(REGEX MATCH "${PATTERN}" IDENTITY "${SECURITY_FOUND_IDENTITY}")
    if (NOT "${IDENTITY}" STREQUAL "")
        string(STRIP "${IDENTITY}" HYPERGRAPH_CODESIGNING)
    endif()
else()
    list(APPEND HYPERGRAPH_LANGUAGES "C")
    list(APPEND HYPERGRAPH_LANGUAGES "CXX")
    if (MINGW)
        list(APPEND HYPERGRAPH_LANGUAGES "RC")
    endif()
endif()

macro(set_option var default type docstring)
	  if (("${type}" STREQUAL "STRING" AND "${var}" STREQUAL "") OR NOT DEFINED ${var})
		    set(${var} ${default})
	  endif()
	  set(${var} ${${var}} CACHE ${type} ${docstring} FORCE)
endmacro()

if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND NOT "${SW_VERS}" STREQUAL "")
    string(REPLACE "." ";" SW_VERS_MAJOR "${SW_VERS}")
    list(POP_FRONT SW_VERS_MAJOR SW_VERS_HEAD)
    set(SW_VERS "${SW_VERS_HEAD}")
    set_option(CMAKE_OSX_DEPLOYMENT_TARGET "${SW_VERS}" STRING "Choose the minimum MacOS deployment version")
endif()
set_option(CMAKE_BUILD_TYPE "Debug" STRING "Choose the type of build config variant (\"Debug\" or \"Release\")")
set_option(HYPERGRAPH_LINKAGE "STATIC" STRING "Choose the type of library linkage for the libhypergraph target (\"STATIC\" or \"SHARED\")")
set_option(HYPERGRAPH_BINARIES "ON" STRING "Whether or not to build the hypergraph executable targets (\"ON\" or \"OFF\")")
set_option(HYPERGRAPH_VIEWER "ON" STRING "Whether or not to build the antiview executable target (\"ON\" or \"OFF\")")
set_option(HYPERGRAPH_TESTING "OFF" STRING "Whether or not to run unit tests (\"ON\" or \"OFF\")")

project(hypergraph VERSION ${HYPERGRAPH_VERSION} LANGUAGES ${HYPERGRAPH_LANGUAGES})

set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_STATIC_LIBRARY_PREFIX "")
if (NOT "${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    set(CMAKE_DEBUG_POSTFIX "${CMAKE_BUILD_TYPE}")
endif()

set(HYPERGRAPH_DEF )
list(APPEND HYPERGRAPH_DEF VERSION="${HYPERGRAPH_VERSION}")
list(APPEND HYPERGRAPH_DEF HYPERGRAPH_CMAKE)
if ("${HYPERGRAPH_LINKAGE}" STREQUAL "SHARED")
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_LIBRARY_TYPE_SHARED)
else()
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_LIBRARY_TYPE_STATIC)
endif()
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_DEBUG)
endif()
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_CLANG)
endif()
if (APPLE)
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_OS_APPLE)
elseif (ANDROID)
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_OS_ANDROID)
elseif (MINGW OR MSVC)
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_OS_WINDOWS)
    if (MINGW)
        list(APPEND HYPERGRAPH_DEF HYPERGRAPH_MINGW)
    endif()
else()
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_OS_LINUX)
endif()
if ("${CMAKE_SIZEOF_VOID_P}" STREQUAL "4")
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_BITNESS_32)
else ()
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_BITNESS_64)
endif ()
include(TestBigEndian)
TEST_BIG_ENDIAN(IS_BIG_ENDIAN)
if (IS_BIG_ENDIAN)
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_ENDIANNESS_BIG)
else()
    list(APPEND HYPERGRAPH_DEF HYPERGRAPH_ENDIANNESS_LITTLE)
endif()

include_directories(${CMAKE_CURRENT_LIST_DIR}/lib)

set(HYPERGRAPH_LIB_DEF )
foreach (DEF IN LISTS HYPERGRAPH_DEF)
    list(APPEND HYPERGRAPH_LIB_DEF ${DEF})
endforeach()
list(APPEND HYPERGRAPH_LIB_DEF HYPERGRAPH_TARGET_TYPE_LIBRARY)

set(HYPERGRAPH_LIB_SRC )
set(HYPERGRAPH_LIB_INC )

list(APPEND HYPERGRAPH_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_gen_algorithms.cpp)
list(APPEND HYPERGRAPH_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_graphs_lib.cpp)
list(APPEND HYPERGRAPH_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_math.cpp)
list(APPEND HYPERGRAPH_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_random.cpp)
list(APPEND HYPERGRAPH_LIB_SRC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_utils.cpp)
list(APPEND HYPERGRAPH_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_debug.h)
list(APPEND HYPERGRAPH_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_gen_algorithms.h)
list(APPEND HYPERGRAPH_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_graphs_lib.h)
list(APPEND HYPERGRAPH_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_math.h)
list(APPEND HYPERGRAPH_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_random.h)
list(APPEND HYPERGRAPH_LIB_INC ${CMAKE_CURRENT_LIST_DIR}/lib/hg_utils.h)
foreach (INC IN LISTS HYPERGRAPH_LIB_INC)
    list(APPEND HYPERGRAPH_LIB_SRC ${INC})
endforeach()

find_package(Boost)
find_package(GSL)

set(HYPERGRAPH_LIBS )
list(APPEND HYPERGRAPH_LIBS ${Boost_LIBRARIES})
list(APPEND HYPERGRAPH_LIBS ${GSL_LIBRARIES})

include_directories(${Boost_INCLUDE_DIR})
link_directories(${Boost_LIBRARY_DIR})
include_directories(${GSL_INCLUDE_DIRS})

add_library(libhypergraph ${HYPERGRAPH_LINKAGE} ${HYPERGRAPH_LIB_SRC})
if ("${HYPERGRAPH_LINKAGE}" STREQUAL "SHARED" AND (APPLE OR WINDOWS))
    install(TARGETS libhypergraph RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/bin FRAMEWORK DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
else()
    install(TARGETS libhypergraph)
endif()
target_compile_features(libhypergraph PRIVATE cxx_std_17)
set_target_properties(libhypergraph PROPERTIES LINKER_LANGUAGE CXX)
target_link_libraries(libhypergraph PRIVATE ${HYPERGRAPH_LIBS})
target_compile_definitions(libhypergraph PRIVATE ${HYPERGRAPH_LIB_DEF})
#set_target_properties(libhypergraph PROPERTIES PUBLIC_HEADER "${HYPERGRAPH_LIB_INC}")

set(HYPERGRAPH_BIN_DEF )
foreach (DEF IN LISTS HYPERGRAPH_DEF)
    list(APPEND HYPERGRAPH_BIN_DEF ${DEF})
endforeach()
list(APPEND HYPERGRAPH_BIN_DEF HYPERGRAPH_TARGET_TYPE_EXECUTABLE)

set(HYPERGRAPH_BIN_SRC_HYPERBOLIC_GRAPH_GENERATOR )
list(APPEND HYPERGRAPH_BIN_SRC_HYPERBOLIC_GRAPH_GENERATOR ${CMAKE_CURRENT_LIST_DIR}/tools/hyperbolic_graph_generator.cpp)

set(HYPERGRAPH_BIN_SRC_GREEDY_ROUTING )
list(APPEND HYPERGRAPH_BIN_SRC_GREEDY_ROUTING ${CMAKE_CURRENT_LIST_DIR}/tools/greedy_routing.cpp)

set(HYPERGRAPH_BIN_SRC_GRAPH_PROPERTIES )
list(APPEND HYPERGRAPH_BIN_SRC_GRAPH_PROPERTIES ${CMAKE_CURRENT_LIST_DIR}/tools/graph_properties.cpp)
list(APPEND HYPERGRAPH_BIN_SRC_GRAPH_PROPERTIES ${CMAKE_CURRENT_LIST_DIR}/tools/stats.cpp)
list(APPEND HYPERGRAPH_BIN_SRC_GRAPH_PROPERTIES ${CMAKE_CURRENT_LIST_DIR}/tools/stats.h)

if ("${HYPERGRAPH_BINARIES}" STREQUAL "ON")
    set(FIRST )
    set(HYPERGRAPH_BIN )
    add_executable(hyperbolic_graph_generator ${HYPERGRAPH_BIN_SRC_HYPERBOLIC_GRAPH_GENERATOR})
    list(APPEND HYPERGRAPH_BIN hyperbolic_graph_generator)
    add_executable(greedy_routing ${HYPERGRAPH_BIN_SRC_GREEDY_ROUTING})
    list(APPEND HYPERGRAPH_BIN greedy_routing)
    add_executable(graph_properties ${HYPERGRAPH_BIN_SRC_GRAPH_PROPERTIES})
    list(APPEND HYPERGRAPH_BIN graph_properties)
    foreach (BIN IN LISTS HYPERGRAPH_BIN)
        add_dependencies(${BIN} libhypergraph)
        install(TARGETS ${BIN} RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin BUNDLE DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
        target_compile_features(${BIN} PRIVATE cxx_std_17)
        set_target_properties(${BIN} PROPERTIES LINKER_LANGUAGE CXX)
        target_link_libraries(${BIN} PRIVATE libhypergraph ${HYPERGRAPH_LIBS})
        target_compile_definitions(${BIN} PRIVATE ${HYPERGRAPH_BIN_DEF})
        if (APPLE)
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/bin COMMENT "Make binary installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/lib COMMENT "Make library installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_INSTALL_PREFIX}/include COMMENT "Make header installation" WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
            if ("${CMAKE_GENERATOR}" MATCHES "Xcode" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Debug" AND NOT "${SW_VERS}" STREQUAL "")
                #set_target_properties(${BIN} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "Apple Development")
                #set_target_properties(${BIN} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "-")
                set_target_properties(${BIN} PROPERTIES XCODE_ATTRIBUTE_CODE_SIGN_ENTITLEMENTS ${CMAKE_CURRENT_LIST_DIR}/hypergraph.entitlements)
                add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --entitlements "${CMAKE_CURRENT_LIST_DIR}/hypergraph.entitlements" --sign - --force --verbose --timestamp --deep $<TARGET_FILE:${BIN}> || :)
                if ("${HYPERGRAPH_LINKAGE}" STREQUAL "SHARED" AND NOT "${FIRST}" STREQUAL " ")
                    add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --entitlements "${CMAKE_CURRENT_LIST_DIR}/hypergraph.entitlements" --sign - --force --verbose --timestamp --deep $<TARGET_FILE:libhypergraph> || :)
                endif()
            endif()
            add_custom_command(TARGET ${BIN} POST_BUILD COMMAND ${CMAKE_INSTALL_NAME_TOOL} -add_rpath "@executable_path/" $<TARGET_FILE:${BIN}> || :)
            string(LENGTH "${HYPERGRAPH_CODESIGNING}" LEN)
            if ("${LEN}" STREQUAL "40" AND "${CMAKE_BUILD_TYPE}" STREQUAL "Release" AND NOT "${SW_VERS}" STREQUAL "")
                add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --sign "${HYPERGRAPH_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:${BIN}> || :)
                if ("${HYPERGRAPH_LINKAGE}" STREQUAL "SHARED" AND NOT "${FIRST}" STREQUAL " ")
                    add_custom_command(TARGET ${BIN} POST_BUILD COMMAND codesign --sign "${HYPERGRAPH_CODESIGNING}" --force --verbose --timestamp --deep $<TARGET_FILE:libhypergraph> || :)
                endif()
            endif()
        endif()
        set(FIRST " ")
    endforeach()
endif()

